name: redisnew

releases:
- name: redis
  version: "0.5"

stemcells:
- alias: default
  os: ubuntu-xenial
  version: "621.330"

instance_groups:
- name: redis
  instances: 6
  azs: [pas-az2]
  vm_type: small
  stemcell: default
  persistent_disk: 1024
  networks:
  - name: sec
  jobs:
  - name: redis
    release: redis
    properties:
      redis:
        cluster-enable: "yes"

update:
  canaries: 1
  max_in_flight: 10
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
